### PR TITLE
zoom ratio src

### PR DESCRIPTION
**Pull request by WEGFan**

### CODE REVIEW

**Comment by WEGFan** [comment]
P.S. The address is 005EDAC0+38, with DRM Free version on Windows 10 64-bit, not tested on other platforms.

**Comment by WEGFan** [comment]
duration: [034A8058+34]+160
step: [034A8058+34]+168

**Comment by Mygod** [comment]
So 22 steps isn't counting down while in “无敌加速状态” right?

**Comment by WEGFan** [comment]
Yes.

**Comment by Mygod** [comment]
Please create a separate PR from now on.

**Comment by WEGFan** [comment]
I clicked new pr and it automatically merge into previous pr.
P.S. The mirror on your website isn't updated.

**Comment by Mygod** [comment]
@WEGFan You must have done something wrong...

Will update later.

**Pull request merged**
