### PR TITLE
another FP bug & delete useless pages

### PR DESCRIPTION
**Pull request by WEGFan**
qq 20170826001318
qq 20170826001938
qq 201708260011331

### CODE REVIEW

**Comment by WEGFan** [comment]
seems it has more bugs...

**Comment by WEGFan** [comment]
qq 20170826004350

**Comment by Mygod** [comment]
Please don't cram everything into one pull request.

**Comment by WEGFan** [comment]
我点create pull request他就自动合并到之前的pr里去了……

**Comment by Mygod** [comment]
你需要在不同的 branch 上 commit。

**Comment by Mygod** [comment]
See at the bottom of this discussion:

> Add more commits by pushing to the **master** branch on **WEGFan/edgefans-archive**.

**Comment by Mygod** [comment]
所以你在等着我帮你弄么……

**Comment by WEGFan** [comment]
不是啊……我昨天有点事（直接回复邮件说地址错误？）

**Pull request closed without merging**
