### PR TITLE
pull request 150216

### PR DESCRIPTION
**Pull request by WEGFan**

### CODE REVIEW

**Comment by Mygod** [comment]
1. How do you know the changes in ttsav.html is correct?
2. Please check if the links to edgefans.tk/mods/edge-epic/for-steam is working correctly.

**Comment by WEGFan** [comment]
1. Email
2. How?

**Comment by Mygod** [comment]
1. Search in files

**Comment by WEGFan** [comment]
worked. ignore that commit
对了手机上能不能玩超过20个prism的关卡？

**Comment by Mygod** [comment]
我记得可以，就是显示坑爹。（可能记错，最好试下）

**Pull request merged**
